# Automated testing with Travis CI!

os:
  - osx

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

notifications:
  email:
    on_success: change
    on_failure: always
